"""Initial migration

Revision ID: 87286c34dc72
Revises: 
Create Date: 2025-09-09 14:06:44.002107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87286c34dc72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_checked', sa.BigInteger(), nullable=True),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('last_error_status', sa.Integer(), nullable=True),
    sa.Column('last_error_time', sa.BigInteger(), nullable=True),
    sa.Column('last_success_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('send_results', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('links')
    # ### end Alembic commands ###
