"""initial

Revision ID: cc8a0ce5970c
Revises: 
Create Date: 2026-07-10 08:20:08.917157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8a0ce5970c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_checked', sa.BigInteger(), nullable=True),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('last_error_status', sa.Integer(), nullable=True),
    sa.Column('last_error_time', sa.BigInteger(), nullable=True),
    sa.Column('last_success_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
