name: Deploy SiteResponseBot

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: doomkirov/site_response_bot:latest
          push: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker pull doomkirov/site_response_bot:latest
            docker stop site_response_bot || true
            docker rm site_response_bot   || true
            
            docker run --rm --name site_response_migrate --network host \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e ADMIN_USER_ID=${{ secrets.ADMIN_USER_ID }} \
              doomkirov/site_response_bot:latest alembic upgrade head

            docker run -d --name site_response_bot --restart on-failure:10 --network host \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e ADMIN_USER_ID=${{ secrets.ADMIN_USER_ID }} \
              doomkirov/site_response_bot:latest
